=== danielddk/danielsoa/TrabajoFinal/persona.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--  tipos  -->

<!--  Dia  -->
 <xsd:simpleType name="tipoDia">
 	<xsd:restriction base="xsd:positiveInteger">
 	<xsd:minInclusive value="1"/>
	<xsd:maxInclusive value="31"/>
 	</xsd:restriction>
 </xsd:simpleType> 
 <!-- Mes --> 
 <xsd:simpleType name="tipoMes">
      <xsd:restriction base="xsd:string">
         <xsd:enumeration value="Enero"/>
         <xsd:enumeration value="Febrero"/>
         <xsd:enumeration value="Marzo"/>
  		 <xsd:enumeration value="Abril"/>
         <xsd:enumeration value="Mayo"/>
         <xsd:enumeration value="Junio"/>
         <xsd:enumeration value="Julio"/>
         <xsd:enumeration value="Agosto"/>
         <xsd:enumeration value="Septiembre"/>
         <xsd:enumeration value="Octubre"/>
         <xsd:enumeration value="Noviembre"/>
         <xsd:enumeration value="Diciembre"/>
      </xsd:restriction>
</xsd:simpleType> 
<!-- aÃ±o -->
 <xsd:simpleType name="tipoAnio">
 	<xsd:restriction base="xsd:positiveInteger">
 	<xsd:minInclusive value="1900"/>
 	<xsd:maxInclusive value="2015"/>
 	</xsd:restriction>
 </xsd:simpleType> 
 <!--  Nombre  -->
 <xsd:simpleType name="tipoNombre">
 	<xsd:restriction base="xsd:string">
 	<xsd:maxLength value="50"/>
 	</xsd:restriction>
 </xsd:simpleType> 

 <xsd:element name="nombre" type="tipoNombre"/>
 <xsd:element name="apellidos" type="tipoNombre"/>
 <xsd:element name="calle" type="tipoNombre"/>
 <xsd:element name="ciudad" type="tipoNombre"/>
 <xsd:element name="provincia" type="tipoNombre"/>
 <xsd:element name="pais" type="tipoNombre"/>

 <xsd:element name="hombre"/>
 <xsd:element name="mujer"/>

 <xsd:element name="nacimiento">
 	<xsd:complexType>
 	<xsd:simpleContent>
 	<xsd:extension base="xsd:string">
 	<xsd:attribute name="dia" type="tipoDia"/>
 	<xsd:attribute name="mes" type="tipoMes"/>
 	<xsd:attribute name="anio" type="tipoAnio"/> 
 	</xsd:extension>
 	</xsd:simpleContent>
 	</xsd:complexType>
 </xsd:element> 

  <xsd:element name="direccion">
 	<xsd:complexType>
 	<xsd:sequence>
 	<xsd:element ref="calle" maxOccurs="unbounded"/>
 	<xsd:element ref="ciudad" maxOccurs="unbounded"/>
 	<xsd:element ref="provincia" maxOccurs="unbounded"/>
  <xsd:element ref="pais" maxOccurs="unbounded"/>
 	</xsd:sequence>
 	</xsd:complexType>
 </xsd:element> 

 <xsd:element name="personas">
 	<xsd:complexType>
 	<xsd:sequence>
 	<xsd:element ref="persona" maxOccurs="unbounded"/>
 	</xsd:sequence>
 	</xsd:complexType>
 </xsd:element>
 
 <xsd:element name="persona">
 	<xsd:complexType>
 	<xsd:sequence>
 	<xsd:element ref="nombre"/>
 	<xsd:element ref="nacimiento" minOccurs="0" maxOccurs="1"/>
 	<xsd:element ref="direccion" maxOccurs="unbounded"/>
 	<xsd:choice>
 	<xsd:element ref="hombre"/>
 	<xsd:element ref="mujer"/>
 	</xsd:choice> 
 	</xsd:sequence>
 	</xsd:complexType>
 </xsd:element> 

 </xsd:schema>

=== danielddk/danielsoa/TrabajoFinal/referencia.xml
<?xml version='1.0' encoding="ISO-8859-1"?>

<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="persona.xsd">

<persona>
    <nombre>Juan Perez</nombre>
    <nacimiento dia="3" mes="Mayo" anio="1986"/>
    <direccion>
       <calle>12 de  Octubre y General Foch </calle>
       <ciudad>Quito</ciudad>
       <provincia>Pichincha</provincia>
       <pais>Ecuador</pais>
    </direccion>
    <hombre/>
 </persona>
 <persona>
    <nombre>Maria Lopez</nombre>
    <direccion>
       <calle>Tamayo n12 y fransisco Salazar</calle>
       <ciudad>Quito</ciudad>
       <provincia>Pichincha</provincia>
       <pais>Ecuador</pais>
    </direccion>
    <direccion>
       <calle>Pichincha 605 entre Clemente Ballen y 10 de agosto</calle>
       <ciudad>Guayaquil</ciudad>
       <provincia>Guayas</provincia>
       <pais>Ecuador</pais>
    </direccion>
    <mujer/>
 </persona>
</personas>
